version: "3.8"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090 # port for qbittorrent
      - 8989:8989 # sonarr port
      - 9117:9117 # jackett port
      - 7878:7878 # radarr
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn #your provider look at gluetun docker info
      - VPN_TYPE=openvpn
      - OPENVPN_USER=yourusername
      - OPENVPN_PASSWORD=yourPassword
      - SERVER_COUNTRIES=Netherlands
      - TZ=Europe/Berlin
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Berlin
      - WEBUI_PORT=8090
    volumes:
      - /home/docker/openvpn-qbit/config/directory:/config
      - /srv/mergerfs/Merge_FS/Torrents:/downloads
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      - gluetun
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
            - PUID=998
            - PGID=100
            - TZ=Europe/Berlin
            - AUTO_UPDATE=true
            - RUN_OPTS=

    volumes:
            - /home/docker/jackett/config:/config
            - /srv/mergerfs/Merge_FS/:/downloads
    network_mode: service:gluetun # run on the vpn network
    depends_on:
         - gluetun
    restart: unless-stopped

  radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=998
            - PGID=100
            - TZ=Europe/Berlin
        volumes:
            - /home/docker/radarr:/config
            - /srv/mergerfs/Merge_FS/Torrents/Filme:/movies
            - /srv/mergerfs/Merge_FS/Torrents:/downloads
        network_mode: service:gluetun # run on the vpn network
        depends_on:
          - gluetun
        restart: unless-stopped

  sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=998
            - PGID=100
            - TZ=Europe/Berlin
        volumes:
            - /home/docker/sonarr:/config
            - /srv/mergerfs/Merge_FS/Torrents/Filme:/tv
            - /srv/mergerfs/Merge_FS/Torrents:/downloads
        network_mode: service:gluetun # run on the vpn network
        depends_on:
         - gluetun
        restart: unless-stopped

